name: Docker Image CD
on:
  push:
    branches: [ "main" ]
env:
  IMAGE_NAME: POC

jobs:
  build:
    name: Build container image
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
#     - name: Get tag
#       id: tag
#       uses: dawidd6/action-get-tag@v1
    - name: Log into registry
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.ACR_ENDPOINT }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
        
    - name: Build & Push
      uses: docker/build-push-action@v2
      with:
        push: true
        build-args: |
#            version=${{ steps.tag.outputs.tag }}
        tags: ${{ secrets.ACR_ENDPOINT }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tag }}
